stages:
  - build

variables:
  APP_VERSION: 1.0.1
  IMAGE_TAG: $REGISTRY_URL/peng-bot/peng-homelab

before_script:
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASS $REGISTRY_URL

test-build:
  stage: build
  image: docker:23.0.6-dind
  tags:
    - docker
  script:
    - docker build -t $IMAGE_TAG:test .

prod-build:
  stage: build
  image: docker:23.0.6-dind
  tags:
    - docker
  script:
    - docker build -t $IMAGE_TAG:$APP_VERSION -t $IMAGE_TAG:latest .
  only:
    variables:
      - $CI_COMMIT_BRANCH == "main"
