stages:
  - build

variables:
  IMAGE_NAME: $CI_REGISTRY/peng-bot/peng-homelab
  VERSION: v1.2.0

test-x64:
  image: docker:23.0.6-dind
  stage: build
  script:
    - docker build --platform linux/amd64 -t $IMAGE_NAME:$VERSION-nightly .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_NAME:$VERSION-nightly
  tags:
    - docker

build-x64:
  image: docker:23.0.6-dind
  stage: build
  script:
    - docker build --platform linux/amd64 -t $IMAGE_NAME:$VERSION .
    - docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:latest
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_NAME:$VERSION
    - docker push $IMAGE_NAME:latest
  tags:
    - docker
  only:
    variables:
      - $CI_COMMIT_BRANCH == "main"

build-arm:
  image: docker:23.0.6-dind
  stage: build
  script:
    - docker build --platform linux/arm64 -t $IMAGE_NAME:$VERSION-arm .
    - docker tag $IMAGE_NAME:$VERSION-arm $IMAGE_NAME:latest-arm
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_NAME:$VERSION-arm
    - docker push $IMAGE_NAME:latest-arm
  tags:
    - docker-arm
  only:
    variables:
      - $CI_COMMIT_BRANCH == "main"