stages:
  - build

variables:
  APP_VERSION: 1.0.1
  IMAGE_TAG: $REGISTRY_URL/peng-bot/peng-homelab

before_script:
  - echo $REGISTRY_PASS | docker login $REGISTRY_URL -u $REGISTRY_USER --password-stdin;

test-build:
  stage: build
  tags:
    - docker
  script:
    - docker build -t $IMAGE_TAG:test .;

prod-build:
  stage: build
  tags:
    - docker
  script:
    - docker build -t $IMAGE_TAG:$APP_VERSION -t $IMAGE_TAG:latest .;
  only:
    variables:
      - $CI_COMMIT_BRANCH == "main"
