stages:
  - build

variables:
  APP_VERSION: 1.0.1
  IMAGE_TAG: $REGISTRY_URL/peng-bot/peng-homelab

before_script:
  - mkdir -p /kaniko/.docker
  - echo "{\"auths\":{\"$REGISTRY_URL\":{\"username\":\"$REGISTRY_USER\",\"password\":\"$REGISTRY_PASS\"}}}" > /kaniko/.docker/config.json

test-build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile Dockerfile --destination $IMAGE_TAG:test

prod-build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile Dockerfile \
      --destination $IMAGE_TAG:$APP_VERSION --destination $IMAGE_TAG:latest \
      --build-arg opts="CGO_ENABLED=0 GOARCH=amd64"
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile Dockerfile \
      --destination $IMAGE_TAG:$APP_VERSION --destination $IMAGE_TAG:latest \
      --build-arg opts="CGO_ENABLED=0 GOARCH=arm64"
  only:
    variables:
      - $CI_COMMIT_BRANCH == "main"
